server:
  servlet:
    context-path: /
  port:
    5000

spring:
  application:
    name: category-service

openapi:
  service:
    title: category-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /category-service/v3/api-docs
  swagger-ui:
    path: /category-service/swagger-ui.html