server:
  servlet:
    context-path: /
  port:
    8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: category-service
          uri: http://localhost:5000
          predicates:
            - Path=/category/** , /category-service/v3/api-docs
          filters:
            - StripPrefix=1
        - id: product-service
          uri: http://localhost:5001
          predicates:
            - Path=/product/** , /product-service/v3/api-docs
          filters:
            - StripPrefix=1
openapi:
  service:
    title: gateway-service doc
    version: 1.0.0
    url: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /category-service/v3/api-docs
        name: Category Service
        primaryName: Category Service
      - url: /product-service/v3/api-docs
        name: Product Service
        primaryName: Product Service